### ISSUE TITLE
Introduce a simplified visitor that would allow recursion.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#100]
I will put in a an skeleton in the code for this issue.

**Comment by yossigil** [comment]
short use case

T result = recurse(myNode).from(T startValue).with( Function from Recurse to T)

for example
start value = 0
Function is lambda expression to return its parameter +1, will give you the total number of nodes in the tree.
I started an API design. Look for class Recurserr, but I won't have much time to do anyhting. 
I think it an excellent design problem. You could even support the following
recurse(n).from(0).postVisit(f);
recurse(n).from(0).preVisit(f);
or 
recurse(n).from(0).pre(f).post(g)
recurse(n).from(0).post(f).pre(g)

**Comment by yossigil** [comment]
- [ ] Did you see this? @NivShalmon

**Comment by dormaayan** [comment]
@yossigil  :
Im not sure I fully understand the purpose of this 2 methods :
```
  /** T is the type of accumulator that is passed to each function, */
  public T go(final Function<Recurser<T>, T> f) {
    return null;
  }

  /** supply self to each node in the tree. */
  public T go(final Consumer<Recurser<T>> f) {
    return null;
  }
```
Should they do a given manipulations over the tree from current to the root and if the answer is yes, how  ?

**Comment by dormaayan** [comment]
@yossigil :
I wrote most of the code and I want to test it,
what do you mean by Mockito and how can I use it to check my code ?

**Comment by yossigil** [comment]
Good job. 

Start wit this to understand how to use `mockito`
```java
  @Test public void asComparisonPrefixlExpression() {
    final PrefixExpression p = mock(PrefixExpression.class);
    doReturn(PrefixExpression.Operator.NOT).when(p).getOperator();
    azzert.isNull(az.comparison(p));
  }
```

**Comment by yossigil** [comment]
@dormaayan: how is it going? @dngreenst and @sakopzon  may need it for their project

**Comment by dormaayan** [comment]
@yossigil : I try to find a way to test my code using Mockito, 
My problem is the mock() doesn't return me a real full object and I get nullExceptions
For example, if I want to create a simple AST for testing, the following doesn't seems to be working right : 
```
  private InfixExpression makeSimpleExpression() {
    InfixExpression e = mock(InfixExpression.class);
    e.setOperator(Operator.PLUS);
    e.setLeftOperand(mock(NumberLiteral.class));
    e.setRightOperand(mock(NumberLiteral.class));
    ((NumberLiteral)e.getLeftOperand()).setToken("3");
    ((NumberLiteral)e.getRightOperand()).setToken("4");
    return e;
  }
```

**Comment by yossigil** [comment]
You have to tell Mock what to return, there is a doReturn option for it.

**Comment by dormaayan** [comment]
@yossigil :

Im aware to the possibilities of doReturn but still, as long as I think about that I find it nearly impossible to mock entire tree with all is complications using mock(), my implementation to Recurser assumes many things that exists in the nodes and it seems nearly impossible to mock the tree with everything

Maybe we can think on another way rather than using mock to test Recurser ?

**Comment by yossigil** [comment]
Use mock to test the basics. To do that, create a simple tree of 5-6 nodes in the test constructor, or @Before method, and then test various aspects of it in @Test functions

**Comment by dormaayan** [comment]
@yossigil  :

Instead of testing it with mock() I tested it with into(), it is much more convenient and better than using mock().
The only problem I need to solve now is that the ASTNode are passed by value and when I do changes in an AST node they aren't reflect in the real AST, I will fix that thing tomorrow, will write a little more intense tests and then I will close that issue.
I think you can open me more issues right now.

**Comment by dormaayan** [comment]
@yossigil :

I solved all the problems and it passes all tests now
I close the issue

**Comment by yossigil** [comment]
@dormaayan  Any chance you can put out a demo elegant use? Perhaps open an issue.
