### ISSUE TITLE
Redo the implementation of Term to deal with Factors.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#101]
Look for class Term, and related classes. Tests, etc. Then, make a duplicate, naming everything to Factor.
It is similar but not identical, i.e., there is no equivalent of minus unary with factors. Double check the associative rule of division, I vaguely remember them being confusing. Make a few cases such 
azzert.that(9/2/8/3/7/4/5, is(1));

(this one is much easier than the other one, so you may want to start here)

**Comment by yossigil** [comment]
Niv, let me give this one to you.

**Comment by yossigil** [comment]
@M4tt30rru FYI: we need this for #76

**Comment by yossigil** [comment]
@dormaayan : you collected some information regarding the arithmetic of long/ int/ division, etc. Please share with @NivShalmon

**Comment by yossigil** [comment]
- [ ] Did you see this? @NivShalmon

**Comment by NivShalmon** [comment]
I saw this, but leaving this aside until kind is more or less ready, since some other issues are already using kind. Will probably start working on it tonight or tommorow, since kind already covers most basic cases

**Comment by NivShalmon** [comment]
I commited a first attempt at some of these classes. It's currently missing two main things (aside for FactorsReorgenazier), simplifiyng prefix expression and removing unnececary 1 such as (1/a*b). I'm not sure if that is realy safe though as that may change the results type or when casting happens. I'll have to look further into this.

**Comment by yossigil** [comment]
Dan and Alex, I forward this to you. You need the drill **before** the environment. Niv started doing it.

**Comment by dngreenst** [comment]
To clarify:

1. What should the lists `up` and `down` contain?  Multipliers and dividers after sort? Something else?

2. Are we interested in any operators besides '*', '/' (and '+', '-', to know where the factor ends)? Which?

**Comment by yossigil** [comment]
The real names should be "nominators" and "denominators", perhaps you should use them.

The other operators, bitwise, etc. are not that common. We will stick with school arithmetic for a long time I think.

**Comment by dngreenst** [comment]
What is the desired result should the input to the FactorCollector/Expander/Reorganizer be a bunch of Terms, as opposed to a single Term? That is: "a+b*c", "a-b+c", instead of "u*y*/(u-3+k*w)". 

I think that as long as we have these actions on Term, and a method to help us distinguish an InfixExpression Factor from InfixExpression Term, doing something on these in Factor is redundant. 

As far as I can tell, every single test that Factor does not pass is of this kind.
@NivShalmon , do you know of any remaining bugs with this class, that I might have missed, when dealing with a single Term?

**Comment by NivShalmon** [comment]
Regading the tests for these classes that are Ignored, they aren't tests the class fail but rather tests that are copied from Term and where not changed yet. This test either test cases that don't have an ideantical case for Factor or are more complex tests I didn't get around to re-write yet. I don't know of any bugs in these classes right now, but more tests are neccesary before we can tell for sure.
Also, while I was working on the code Factor.asExpression() had a bug when the factor was a fraction, but this function doesn't seem to be used anywhere right now. I'm not sure if I added tests for that one or not, so you should look into that if you haven't.

**Comment by yossigil** [comment]
Thanks Niv! +1

**Comment by dngreenst** [comment]
Fixed Factor.asExpression() bug, and added a couple of tests.

Assuming we agree that for a non Term input, the Factor operations are undefined, I think this issue can be closed.

I think this is a reasonable assumption to make, if we introduce a dispatcher class for these classes.

**Comment by yossigil** [comment]
I am not sure I understand your assumption

**Comment by dngreenst** [comment]
I'm trying to understand if an input InfixExpression whose primary operator is "-" or "+" is a legitimate input to Factor, FactorCollector, FactorExpander and FactorReorganizer (hereforth - Factor classes).

If this input is legitimate, what should be the output?

My assumption is that such input is not legitimate, and hence, the result  of operations of these classes does not have to be defined.

Each mathematical expression with "-","+","\*","/" is either a list of factors with "\*","/" primary operands between them, or a list of terms with "+","-" primary operands between them. 

If we can distinguish between these two cases (seems doable) using an outside class, we could implement Expand/Reorganize functions that will call FactorExpander/FactorReorganizer/TermExpander/TermReorganizer as necessary (TermCollector & FactorCollector is a different case, I think - the user clearly wants to know which of the two he is dealing with).

Since Factor classes, in this case, will not be called directly by an unknowing user, I think the outcome could be left undefined.  

Alternatively, we could return empty lists for Collector, and unchanged expressions for Expander/Reorganizer.

**Comment by yossigil** [comment]
Please add github to your code and close this one.
