### ISSUE TITLE
Exception -> e  /. Expression -> x

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan-refactoring#31]
Add wring and add configuration option.

**Comment by OriRoth** [comment]
You can try doing it using VariableChangeName as a parent wring... see VariableRenameUnderscoreToDoubleUnderscore as an example. It will probably be much easier that way

**Comment by sakopzon** [comment]
Could you please give an example of "from" and "to" because we didn't understand the issue.

**Comment by yossigil** [comment]
````java
catch (Exception e) {
throw e
}
```

Currently, Exception, Expression, Extra, etc. Are abbreviated to 'e'. Change the abbreviation to `x`

**Comment by sakopzon** [comment]
We tried two different approaches to this issue, and came to the understanding that the implementation MUST use the Environment! We can propose a crippled solutions threw JavaTypeNameParser each of which will fall in different tests just for practicing. Or we can keep thinking about how to finish with the Env and return to it afterwards with tools for an elegant solution (now we read the wizard, step, hop and have some ideas).

**Comment by yossigil** [comment]
No. Just look at the name, and at TypeNameParser.
If the name begins with something start starts with EX, e.g., example, exception, expression, use "x", since very few words in English start with an ex. Do not touch the environment.

**Comment by yossigil** [comment]
How can you close it with this
![image](https://cloud.githubusercontent.com/assets/12775400/18210745/ba21cf2c-7142-11e6-98c0-9c866487afbd.png)

**Comment by dngreenst** [comment]
Spartanized everything that seemed reasonable (that is, not tests).

**Comment by yossigil** [comment]
Spartanize everything . We want to see the spartanization clean. So, any violation will pop out

**Comment by dngreenst** [comment]
There are 22 Spartanizations left: 

5 suggestions seem buggy (which is something I should have alerted you of, and would have, if it did not slip from my mind in the somewhat hazy mass spartanization):

1 in ApplySpartanizationHandler - line 39, suggesting to switch r.size() <= 0 to r.isEmpty(). I did not spartanize this, because r is of type Range, and it does not have class isEmpty(). The suggested spartanization causes a compilation problem. 

The info page shows 3 spartanizations in DeclarationInitializersReturnAssignment. Only 1 actually appears when looking into the class. Trying to spartanize does not do anything.

 1 Spartanization in CleanupHandler, line 86. The result of the spartanization is a compilation error. 

1 more spartanization is ArithmeticTest and and 16 more in PrudentTypeTest. It seems to me that spartanizing these parts will undermine the purpose of the tests.

**Comment by yossigil** [comment]
@dormaayan : can you fix the tests in ArithmeticTest so that they do not loose their essence when spartanized. Use field variables.

@dngreenst : add an `isEmpty' method to class Range, let @dormaayan fix this one, but do open a separate issue for the rest. Lable it "bug'. Include an example.

**Comment by dormaayan** [comment]
@yossigil : Currently the plugin ofers me 7 possible correction and none of them is in ArithmeticTest

**Comment by yossigil** [comment]
The general rule is: don't disable spartanization in the plugin. If you can manage these 7, great. Else bring them up here
